name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build Signed APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle' # Cache Gradle dependencies

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Cache Flutter dependencies

      - name: Get version from pubspec.yaml
        id: version
        run: |
          version=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "Current version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get packages
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties
        working-directory: android

      - name: Build APK (Release)
        env:
          BACKEND_BASE_URL: ${{ secrets.BACKEND_BASE_URL_PROD }}
        run: |
          flutter build apk --release --split-per-abi \
            --dart-define=BACKEND_BASE_URL=$BACKEND_BASE_URL

      - name: Generate Release Info
        id: release_info
        run: |
          echo "date=$(TZ='Asia/Jakarta' date +'%A, %d %b %Y %H:%M WIB')" >> $GITHUB_OUTPUT
          # Tag menggunakan versi + short commit hash agar unik
          echo "tag=v${{ steps.version.outputs.version }}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/flutter-apk/app-*-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release_info.outputs.tag }}
          name: "Release ${{ steps.version.outputs.version }}"
          body: |
            ## ðŸš€ New Build
            **Version**: `${{ steps.version.outputs.version }}`
            **Built at**: ${{ steps.release_info.outputs.date }}
            **Commit**: ${{ github.sha }}
            
            ### Downloads
            - `armeabi-v7a`: HP Android lama/biasa
            - `arm64-v8a`: HP Android modern
            - `x86_64`: Emulator